### ISSUE TITLE
Windows/Python3 make install failed

### ISSUE THREAD

**Issue by librehat** [randombit/botan#39] opened 2015-01-07 15:08 UTC
```
 make install
cp doc/manual/*.rst build/docs/manual
src/scripts/install.py --destdir=D:/MinGW/msys/home/Symeon/botan_x64 --bindir=bin --libdir=lib --docdir=share/doc --includedir=include
  File "D:\MinGW\msys\home\Symeon\Botan-1.11.12\src\scripts\install.py", line 94
    exe_mode = 0777
                  ^
SyntaxError: invalid token
makefile:1360: recipe for target 'install' failed
make: *** [install] Error 1
```

I tried to comment line 94 and line 100, but still get failed.

Env: Windows (MinGW) + Python 3.4.2

**Comment by randombit** [comment] 2015-01-07 15:54
I just recently fixed this in trunk and it at least works under Python 3.3.5 on Linux now. Can you try latest trunk or just apply this commit directly https://github.com/randombit/botan/commit/6198946dbb5a864ab0aa9ce8d27c920423634827

**Comment by librehat** [comment] 2015-01-07 23:09
```
$ make install
cp doc/manual/*.rst build/docs/manual
src/scripts/install.py --destdir=D:/MinGW/msys/home/Symeon/botan_x64 --bindir=bin --libdir=lib --docdir=share/doc --includedir=include
Traceback (most recent call last):
  File "D:\MinGW\msys\home\Symeon\botan-net.randombit.botan\src\scripts\install.py", line 21, in <module>
    from botan_version import release_major, release_minor, release_patch
ImportError: No module named 'botan_version'
makefile:1355: recipe for target 'install' failed
make: *** [install] Error 1
```

Another error surfaced.

**Comment by randombit** [comment] 2015-01-08 14:45
The install script was assuming the current working directory was part of PYTHONPATH, which happened to work on my machines. Can you check again with latest trunk?

**Comment by librehat** [comment] 2015-01-08 17:10
```
$ make install
cp doc/manual/*.rst build/docs/manual
src/scripts/install.py --destdir=D:/MinGW/msys/home/Symeon/botan_x64 --bindir=bin --libdir=lib --docdir=share/doc --includedir=include
  ERROR: Failure: [Errno 2] No such file or directory: '.\\botan'
   INFO: Traceback (most recent call last):
  File "D:\MinGW\msys\home\Symeon\botan-net.randombit.botan\src\scripts\install.py", line 211, in <module>
    sys.exit(main())
  File "D:\MinGW\msys\home\Symeon\botan-net.randombit.botan\src\scripts\install.py", line 186, in main
    copy_executable(os.path.join(out_dir, app_exe), os.path.join(bin_dir, app_exe))
  File "D:\MinGW\msys\home\Symeon\botan-net.randombit.botan\src\scripts\install.py", line 108, in copy_executable
    shutil.copyfile(src, dest)
  File "d:\Python34\lib\shutil.py", line 107, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '.\\botan'

makefile:1355: recipe for target 'install' failed
make: *** [install] Error 1
```

**Comment by webmaster128** [comment] 2015-06-16 21:10
@librehat Are you using mingw to compile? mingw should produce `botan.exe` as an output file. But the install script looks for `botan` without suffix. Can that be the error?

**Comment by librehat** [comment] 2015-06-17 11:06
@webmaster128 Yes I used MInGW to compile. As I reported before, I believe the dev team is still working on new features or so. They probably need to test the compilation process on Windows before move `1.11` to stable. I'm using `1.10` in the meantime.

**Comment by webmaster128** [comment] 2015-07-01 09:00
@librehat The dev team is Jack and me at the moment ;) I fixed a lot of build system stuff before 1.11.17. Can you try it again using 1.11.17? If there are problems left, those could be targeted for 1.11.18.

**Comment by librehat** [comment] 2015-07-05 17:43
```
python configure.py --prefix=$HOME/botan_x86 --disable-shared --os=mingw --cpu=i686 --cc=gcc
make -j4
```
And the result is
```
g++ -pthread -fstack-protector -std=c++11 -D_REENTRANT -O2 -Wall -Wextra -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Ibuild\include -c src\tests\nist_x509.cpp -o build\obj\test\nist_x509.o
src\cmd\tls_server.cpp:29:24: fatal error: sys/socket.h: No such file or directory
 #include <sys/socket.h>
                        ^
compilation terminated.
makefile:1368: recipe for target 'build\obj\app\tls_server.o' failed
make: *** [build\obj\app\tls_server.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by randombit** [comment] 2015-07-06 04:22
@librehat Can you try the 1.11.18 release and see if that improves the situation for you?

**Comment by librehat** [comment] 2015-07-12 19:33
Now it failed with `make install`. The script should generate slash '/' instead of anti-slash '\' when using MinGW.

```
$ make install
cp doc\manual\*.rst build\docs\manual
cp: cannot stat `docmanual*.rst': No such file or directory
makefile:1541: recipe for target 'docs' failed
make: *** [docs] Error 1
```

After I manually changed '\' to '/', the error becomes:

```
$ make install
cp doc/manual/*.rst build/docs/manual
src/scripts/install.py --destdir=D:/MinGW/msys/home/Symeon/botan_x86 --build-dir="build" --bindir=bin --libdir=lib --docdir=share/doc --includedir=include
Traceback (most recent call last):
  File "src/scripts/install.py", line 22, in <module>
    import combine_relnotes
ImportError: No module named 'combine_relnotes'
makefile:1544: recipe for target 'install' failed
make: *** [install] Error 1
```

**Comment by webmaster128** [comment] 2015-07-13 11:25
The second error is a regression bug (1.11.17 -> 1.11.18) and [will be fixed in 1.11.19](https://github.com/randombit/botan/issues/181).

The first one though might be tricky. The make target `make doc` is generated while configure is running and uses [os.sep](https://docs.python.org/2/library/os.html#os.sep) and [os.path.join](https://docs.python.org/2/library/os.path.html#os.path.join), which should know what path seperator to use.

1. Did you run the `./configure.py` in a Windows or in an MingGW environment?
2. What is the output of `python -c "import os; print(os.sep)"`?

**Comment by webmaster128** [comment] 2015-07-13 11:39
Problem 1 is covered in great detail in this mailing list: [python and directory separators](http://sourceforge.net/p/msys2/mailman/msys2-users/thread/CAOYw7dspg6NquVq7paF8Ek_AnVyXwyczS-w5_ihNsVyyGeNL5Q%40mail.gmail.com/)

The question is whether we can work around that. Given that we can generate Makefiles for Windows on Linux, why shouldn't it be possible to generate Linux Makefiles from Windows. In this case the output of `os.sep` must not be part of the output Makefile. But this is some kind of nice to have longtime goal.

I think the best help for you is this quote:

> I found a workaround; use Cygwin bash, Cygwin sed to run this command.
Then the msys64 'make install' succeeds.

**Comment by librehat** [comment] 2015-07-13 18:42
@webmaster128 I'd rather think the `os.sep` shouldn't be used if I explicitly set `--os=mingw` in `configure.py`. And I'd rather use Notepad++ to replace all '\' to '/' instead of installing Cygwin to just do a configure job.

**Comment by webmaster128** [comment] 2015-07-13 19:58
> I'd rather think the os.sep shouldn't be used if I explicitly set --os=mingw in configure.py

I am with you on that point but sadly, that is not a trivial thing to do, because there are paths that need to work for the OS running `./configure.py` and there are paths that need to work for the OS running the Makefile. There are 50+ occurrences of either `os.sep` or `os.path.join`.

> And I'd rather use Notepad++ to replace all '\' to '/' instead

Sure, use the tools that suite you best and share your insights with the community :) Just take care that you don't replace the escape characters, e.g. before line endings (line ~50-400).

Since there is no support at all of generating a Makefile for another platform, I do not see a sustainable fix in the foreseeable future. And at the end of the day this is a MinGW bug, not a Botan bug.

**Comment by webmaster128** [comment] 2015-07-21 20:37
@librehat What MinGW shell are you using? I installed Mysys2, which comes with Python 3.4.3. In This version, python uses out the correct path separator "/".

**Comment by librehat** [comment] 2015-07-23 15:00
@webmaster128 I used the old MSYS.

**Comment by webmaster128** [comment] 2015-07-24 17:41
I am closing this because what you described is either done in Botan 1.11.19 coming on August, 3rd or a known issue of MSYS that does not occur in all MinGW setups. If you have follow-up problems with 1.11.19, just open a new issue for that specific thing. Thanks!

**Closed by webmaster128** 2015-07-24 17:41 UTC
Labels: bug
