### ISSUE TITLE
LaTeX doc build fails on the current master (with current TeXLive-2016)

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#746] opened 2016-12-01 01:38 UTC
```
$ sudo make install
Password:
sphinx-build -c ./src/build-data/sphinx -b html ./doc/manual build/docs/manual
Running Sphinx v1.4.9
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
no targets are out of date.
build succeeded.
sphinx-build -c ./src/build-data/sphinx -b latex ./doc/manual build/docs/manual
Running Sphinx v1.4.9
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
processing botan.tex... contents index building python cli firststep secmem rng filters hash symmetric_crypto pubkey mceliece x509 ocsp tls credentials_manager bigint lowlevel kdf pbkdf passhash cryptobox srp fpe compression versions ffi pkcs11 
resolving references...
writing... done
copying TeX support files...
done
build succeeded.
./src/scripts/install.py --destdir=/opt/local --build-dir="build" --bindir=bin --libdir=lib --docdir=doc --includedir=include
   INFO: Botan 1.11.34 installation complete
$ cd build/docs/manual/
$ make
pdflatex  'botan.tex'
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./botan.tex
LaTeX2e <2016/03/31> patch level 3
Babel <3.9r> and hyphenation patterns for 83 language(s) loaded.
(./sphinxmanual.cls
Document Class: sphinxmanual 2009/06/02 Document class (Sphinx manual)
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/report.cls
Document Class: report 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/size10.clo))) (./iftex.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/inputenc.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/utf8.def
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/t1enc.dfu)
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/ot1enc.dfu)
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/omsenc.dfu)))
(/usr/local/texlive/2016/texmf-dist/tex/latex/cmap/cmap.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/fontenc.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/t1enc.def)<<t1.cmap>>)
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(/usr/local/texlive/2016/texmf-dist/tex/generic/babel/babel.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/babel-english/english.ldf
(/usr/local/texlive/2016/texmf-dist/tex/generic/babel/babel.def)))
(/usr/local/texlive/2016/texmf-dist/tex/latex/psnfss/times.sty) (./fncychap.sty
) (/usr/local/texlive/2016/texmf-dist/tex/latex/tools/longtable.sty)
(./sphinx.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/textcomp.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/ts1enc.def
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/ts1enc.dfu)))
(/usr/local/texlive/2016/texmf-dist/tex/latex/fancybox/fancybox.sty
Style option: `fancybox' v1.4 <2010/05/15> (tvz)
) (/usr/local/texlive/2016/texmf-dist/tex/latex/titlesec/titlesec.sty)
(./tabulary.sty (/usr/local/texlive/2016/texmf-dist/tex/latex/tools/array.sty))
 (/usr/local/texlive/2016/texmf-dist/tex/latex/base/makeidx.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/framed/framed.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/ifthen.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics-def/pdftex.def
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)))
(/usr/local/texlive/2016/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz)
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/keyval.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/threeparttable/threeparttable.sty
) (/usr/local/texlive/2016/texmf-dist/tex/latex/mdwtools/footnote.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/wrapfig/wrapfig.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/parskip/parskip.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/alltt.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/upquote/upquote.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/float/float.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)))
(/usr/local/texlive/2016/texmf-dist/tex/generic/pdftex/pdfcolor.tex)
(/usr/local/texlive/2016/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(/usr/local/texlive/2016/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/kvoptions.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2016/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/local/texlive/2016/texmf-dist/tex/latex/hyperref/puenc.def)
(/usr/local/texlive/2016/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver (autodetected): hpdftex.

(/usr/local/texlive/2016/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/hypcap.sty)
(./newfloat.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/capt-of/capt-of.sty)
(./needspace.sty)
** (sphinx) defining (legacy) text style macros without \sphinx prefix
** if clashes with packages, set latex_keep_old_macro_names=False in conf.py
) (/usr/local/texlive/2016/texmf-dist/tex/latex/multirow/multirow.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/eqparbox/eqparbox.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/environ/environ.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/trimspaces/trimspaces.sty)))
Writing index file botan.idx
No file botan.aux.
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/ts1cmr.fd)
(/usr/local/texlive/2016/texmf-dist/tex/latex/psnfss/t1ptm.fd)
(/usr/local/texlive/2016/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/grfext.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
(/usr/local/texlive/2016/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
! TeX capacity exceeded, sorry [input stack size=5000].
\font@name ->
             \T1/ptm/m/n/10 
l.143 \tableofcontents
                      
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on botan.log.
make: *** [botan.pdf] Error 1
$ 
```

[botan.log.txt](https://github.com/randombit/botan/files/623625/botan.log.txt)

**Comment by mouse07410** [comment] 2016-12-01 04:34
Probably a local issue: re-building everything and re-installing resolved it.

**Comment by mouse07410** [comment] 2016-12-01 20:17
Sorry, have to re-open. On another machine this issue does not go away. Everything seems normal, Mac OS X El Capitan 10.11.6, Xcode-8.1, etc.

```
$ ./configure.py --prefix=/opt/local --without-unaligned-mem --with-openssl --with-boost --with-lzma --with-bzip2 --with-zlib --with-sqlite3 --with-python-version=2.7 --with-sphinx --enable-modules=pkcs11 --cc-abi-flags='-maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4 -msse4.2 -Os -Ofast -I/opt/local/include'
   INFO: ./configure.py invoked with options "--prefix=/opt/local --without-unaligned-mem --with-openssl --with-boost --with-lzma --with-bzip2 --with-zlib --with-sqlite3 --with-python-version=2.7 --with-sphinx --enable-modules=pkcs11 --cc-abi-flags=-maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4 -msse4.2 -Os -Ofast -I/opt/local/include"
   INFO: Platform: OS="Darwin" machine="x86_64" proc="i386"
   INFO: Guessing target OS is darwin (use --os to set)
   INFO: Guessing to use compiler clang (use --cc to set)
   INFO: Guessing target processor is a x86_64/x86_64 (use --cpu to set)
   INFO: Target is clang-darwin-x86_64-x86_64
   INFO: Skipping, incompatible OS - cryptoapi_rng locking_allocator win32_stats
   INFO: Skipping, requires external dependency - boost bzip2 lzma openssl pkcs11 sqlite3 tpm zlib
   INFO: Loading modules adler32 aead aes aes_ni aes_ssse3 aont asn1 auto_rng base base64 bcrypt bigint blake2 block blowfish boost bzip2 camellia cascade cast cbc cbc_mac ccm cecpq1 certstor_sql certstor_sqlite3 cfb chacha chacha20poly1305 chacha_sse2 clmul cmac codec_filt comb4p compression crc24 crc32 cryptobox ctr curve25519 darwin_secrandom datastor des dev_random dh dl_algo dl_group dlies dsa dyn_load eax ec_gfp ec_group ecb ecc_key ecdh ecdsa ecgdsa ecies eckcdsa elgamal eme_oaep eme_pkcs1 eme_raw emsa1 emsa_pkcs1 emsa_pssr emsa_raw emsa_x931 entropy fd_unix ffi filters fpe_fe1 gcm gmac gost_28147 gost_3410 gost_3411 hash hash_id hex hkdf hmac hmac_drbg http_util idea idea_sse2 kasumi kdf kdf1 kdf1_iso18033 kdf2 keccak keypair lion lzma mac mce mceies md4 md5 mdx_hash mgf1 misty1 mode_pad modes mp newhope noekeon noekeon_simd numbertheory ocb ofb openssl par_hash passhash9 pbes2 pbkdf pbkdf1 pbkdf2 pem pk_pad pkcs11 poly1305 prf_tls prf_x942 proc_walk pubkey rc4 rdrand rdrand_rng rdseed rfc3394 rfc6979 rmd160 rng rsa salsa20 seed serpent serpent_simd sessions_sql sessions_sqlite3 sha1 sha1_sse2 sha2_32 sha2_64 sha3 shake shake_cipher simd siphash siv skein sp800_108 sp800_56c sqlite3 srp6 stateful_rng stream system_rng threefish threefish_avx2 tiger tls tls_cbc tss twofish utils whirlpool x509 x919_mac xmss xtea xts zlib
   INFO: Enabling use of external dependency boost
   INFO: Enabling use of external dependency bzip2
   INFO: Enabling use of external dependency lzma
   INFO: Enabling use of external dependency openssl
   INFO: Enabling use of external dependency pkcs11
   INFO: Enabling use of external dependency sqlite3
   INFO: Enabling use of external dependency zlib
   INFO: Assuming CPU is little endian
   INFO: Using symlink to link files into build dir (use --link-method to change)
   INFO: Botan 1.11.34 (unreleased undated) build setup is complete

$ make clean && make -j 4 all && ./botan-test && ./botan-test pkcs11 --pkcs11-lib=/opt/local/lib/softhsm/libsofthsm2.so  && sudo make install && sudo chown -R ur20980 * && cd build/docs/manual/ && make && cp botan.pdf ~/Documents/botan-1.11.pdf  && cp botan.pdf /Volumes/ur20980/botan-1.11.pdf  && make clean && cd ../../.. && make clean 
clang++  -m64 -pthread -stdlib=libc++ -maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4 -msse4.2 -Os -Ofast -I/opt/local/include -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -fstack-protector -O3 -Wall -Wextra -Wpedantic -Wshadow -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wunreachable-code -Ibuild/include -Ibuild/include/external -c ./src/lib/asn1/alg_id.cpp -o build/obj/lib/asn1_alg_id.o
clang++  -m64 -pthread -stdlib=libc++ -maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4 -msse4.2 -Os -Ofast -I/opt/local/include -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -fstack-protector -O3 -Wall -Wextra -Wpedantic -Wshadow -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wunreachable-code -Ibuild/include -Ibuild/include/external -c ./src/lib/asn1/asn1_alt_name.cpp -o build/obj/lib/asn1_alt_name.o
clang++  -m64 -pthread -stdlib=libc++ -maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4 -msse4.2 -Os -Ofast -I/opt/local/include -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -fstack-protector -O3 -Wall -Wextra -Wpedantic -Wshadow -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wunreachable-code -Ibuild/include -Ibuild/include/external -c ./src/lib/asn1/asn1_attribute.cpp -o build/obj/lib/asn1_attribute.o
. . . . .
KCS11 X509 cert import ran 2 tests all ok
Tests complete ran 88 tests all tests ok
Password:
sphinx-build -c ./src/build-data/sphinx -b html ./doc/manual build/docs/manual
Running Sphinx v1.4.9
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 29 source files that are out of date
updating environment: 29 added, 0 changed, 0 removed
reading sources... [100%] x509                                                                                     
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] x509                                                                                      
generating indices... genindex py-modindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.
sphinx-build -c ./src/build-data/sphinx -b latex ./doc/manual build/docs/manual
Running Sphinx v1.4.9
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
processing botan.tex... contents index building python cli firststep secmem rng filters hash symmetric_crypto pubkey mceliece x509 ocsp tls credentials_manager bigint lowlevel kdf pbkdf passhash cryptobox srp fpe compression versions ffi pkcs11 
resolving references...
writing... done
copying TeX support files...
done
build succeeded.
./src/scripts/install.py --destdir=/opt/local --build-dir="build" --bindir=bin --libdir=lib --docdir=doc --includedir=include
   INFO: Botan 1.11.34 installation complete
pdflatex  'botan.tex'
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./botan.tex
LaTeX2e <2016/03/31> patch level 3
Babel <3.9r> and hyphenation patterns for 83 language(s) loaded.
(./sphinxmanual.cls
Document Class: sphinxmanual 2009/06/02 Document class (Sphinx manual)
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/report.cls
Document Class: report 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/size10.clo))) (./iftex.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/inputenc.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/utf8.def
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/t1enc.dfu)
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/ot1enc.dfu)
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/omsenc.dfu)))
(/usr/local/texlive/2016/texmf-dist/tex/latex/cmap/cmap.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/fontenc.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/t1enc.def)<<t1.cmap>>)
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(/usr/local/texlive/2016/texmf-dist/tex/generic/babel/babel.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/babel-english/english.ldf
(/usr/local/texlive/2016/texmf-dist/tex/generic/babel/babel.def)))
(/usr/local/texlive/2016/texmf-dist/tex/latex/psnfss/times.sty) (./fncychap.sty
) (/usr/local/texlive/2016/texmf-dist/tex/latex/tools/longtable.sty)
(./sphinx.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/textcomp.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/ts1enc.def
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/ts1enc.dfu)))
(/usr/local/texlive/2016/texmf-dist/tex/latex/fancybox/fancybox.sty
Style option: `fancybox' v1.4 <2010/05/15> (tvz)
) (/usr/local/texlive/2016/texmf-dist/tex/latex/titlesec/titlesec.sty)
(./tabulary.sty (/usr/local/texlive/2016/texmf-dist/tex/latex/tools/array.sty))
 (/usr/local/texlive/2016/texmf-dist/tex/latex/base/makeidx.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/framed/framed.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/ifthen.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics-def/pdftex.def
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)))
(/usr/local/texlive/2016/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz)
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/keyval.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/threeparttable/threeparttable.sty
) (/usr/local/texlive/2016/texmf-dist/tex/latex/mdwtools/footnote.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/wrapfig/wrapfig.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/parskip/parskip.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/alltt.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/upquote/upquote.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/float/float.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)))
(/usr/local/texlive/2016/texmf-dist/tex/generic/pdftex/pdfcolor.tex)
(/usr/local/texlive/2016/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(/usr/local/texlive/2016/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/kvoptions.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2016/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/local/texlive/2016/texmf-dist/tex/latex/hyperref/puenc.def)
(/usr/local/texlive/2016/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver (autodetected): hpdftex.

(/usr/local/texlive/2016/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/hypcap.sty)
(./newfloat.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/capt-of/capt-of.sty)
(./needspace.sty)
** (sphinx) defining (legacy) text style macros without \sphinx prefix
** if clashes with packages, set latex_keep_old_macro_names=False in conf.py
) (/usr/local/texlive/2016/texmf-dist/tex/latex/multirow/multirow.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/eqparbox/eqparbox.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/environ/environ.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/trimspaces/trimspaces.sty)))
Writing index file botan.idx
No file botan.aux.
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/ts1cmr.fd)
(/usr/local/texlive/2016/texmf-dist/tex/latex/psnfss/t1ptm.fd)
(/usr/local/texlive/2016/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/grfext.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
(/usr/local/texlive/2016/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
! TeX capacity exceeded, sorry [input stack size=5000].
\font@name ->
             \T1/ptm/m/n/10 
l.143 \tableofcontents
                      
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on botan.log.
make: *** [botan.pdf] Error 1
$ 
```

[botan.log.txt](https://github.com/randombit/botan/files/625653/botan.log.txt)

**Comment by mouse07410** [comment] 2016-12-01 20:24
It looks like using `py27-sphinx` now fails LaTeX. But using `py35-sphinx` succeeds.
```
$ port select --list sphinx
Available versions for sphinx:
	none
	py27-sphinx
	py35-sphinx (active)
$ 
```

I can accept this as a workaround. Would you like to document it somewhere, or...?

**Comment by randombit** [comment] 2016-12-02 00:54
I think really this is a bug for either Sphinx, Python, or whatever distribution of TeX OS X uses (not sure who).

**Comment by mouse07410** [comment] 2016-12-02 02:41
Probably Sphinx... The only thing that varies between successful and failed runs...

Could you report to Sphinx developers, or should I?

**Comment by randombit** [comment] 2016-12-02 14:39
You should probably report it since you're the one who can reproduce it.

**Comment by mouse07410** [comment] 2016-12-02 20:37
OK, will do. Closing this issue.

**Comment by mouse07410** [comment] 2016-12-13 21:32
Here's the answer from the Sphinx community:

> This is a character encoding problem which causes an infinite loop with \textcopyright.
> 
```
\author{Jack Lloyd \and Daniel Neus \and RenÃ© Korthaus \and Juraj Somorovsky \and Tobias Niemann}
```
> Can you use the following in your `src/build-data/sphinx/conf.py` :
>
> 
```
latex_documents = [
  ('contents', 'botan.tex', u'Botan Reference Manual',
   u'Jack Lloyd \\and Daniel Neus \\and Ren\u00e9 Korthaus \\and Juraj Somorovsky \\and Tobias Niemann', 'manual'),
]
```
> and try again? I don't know enough of Python aspects of Sphinx to tell if this is a Sphinx problem.

I confirm that the proposed change fixes the Sphinx for both Python-2.7 and Python-3.5.

Could you make the change please, or would you insist on a PR for this one-character change? :-)

**Comment by cordney** [comment] 2016-12-13 21:55
I also got a similar error from pdflatex just today, on another machine (mine works fine, so seems to be related to sphinx/latex version). Ooops, sorry my name is causing these problems ;). The fix @mouse07410 suggests works fine for me, too.

**Comment by mouse07410** [comment] 2016-12-13 22:28
> ...seems to be related to sphinx/latex version...

Probably more so to Python version. As I said above - it works without patch with Python-3.5 (and sphinx being installed for Python-3.5). But with the proposed patch it works with both Python-3.5 *and* Python-2.7.

**Comment by randombit** [comment] 2016-12-14 18:59
Should be fixed now, thanks for following up on this.

Probably pdf build should be added to the docs CI target - it seems like there are a surprising number of regressions here even when everything is fine with the HTML output.

**Closed by randombit** 2016-12-14 18:59 UTC

**Comment by mouse07410** [comment] 2016-12-15 00:19
> Probably pdf build should be added to the docs CI target - it seems like there are a surprising number of regressions here even when everything is fine with the HTML output.

Yes please!!
