### ISSUE TITLE
Consistent use of string pointer relative to UNICODE in MSVC build

### ISSUE THREAD

**Issue by pgp** [randombit/botan#2254] opened 2020-02-05 12:32 UTC
(Using Visual Studio Build Tools 2019)

The method ```HCERTSTORE open_cert_store(const char* cert_store_name)``` in ```src/lib/x509/certstor_system_windows/certstor_windows.cpp``` accepts a non-templated string pointer (const char*), but internally calls the ```CertOpenSystemStore``` API, whose actual signature depends on whether a build is UNICODE or not (that is, resolving to CertOpenSystemStoreW or CertOpenSystemStoreA, respectively). I am aware of the fact that developing a robust unicode-aware management for windows requires a lot of effort, but it would be useful at least to explicitly use **CertOpenSystemStoreA** in this case, since the signature of open_cert_store doesn't use templates, in order to avoid build failure if UNICODE is enabled.

**Comment by randombit** [comment] 2020-02-05 14:08
Thanks for the report. We need to add a Unicode build to CI to detect issues like this.

**Comment by hrantzsch** [comment] 2020-02-06 09:42
The issue can easily be reproduced by setting the `-DUNICODE -D_UNICODE` cxx flags. What's the best way to teach the CI to do this?
`ci_build.py` could either get a new option `--extra-cxxflags`, which it forwards to `configure.py`, or directly an option `--with-unicode` that sets the extra flags.

**Comment by randombit** [comment] 2020-02-06 12:56
@hrantzsch In #2256 I went with --extra-cxxflags exactly as you suggested, since we may well need similar functionality for other cases in the future. But I only used `/DUNICODE` - is `/D_UNICODE` also required here?

**Comment by hrantzsch** [comment] 2020-02-07 03:17
`/DUNICODE` is enough to reproduce the issue.

`_UNICODE` is for the headers of the C runtime (https://stackoverflow.com/a/7953476) and it seems common practice to define both. I'm not sure if it can cause any trouble but I think we want to use both.

**Comment by randombit** [comment] 2020-02-08 16:42
Fixed in master, and now we check Unicode builds in CI which should prevent similar regressions. Thanks again for the report.

**Closed by randombit** 2020-02-08 16:42 UTC
