### ISSUE TITLE
2.17.0/ppc64 build failure

### ISSUE THREAD

**Issue by gcsideal** [randombit/botan#2463] opened 2020-11-07 06:31 UTC
Packaged Botan 2.17.0 for Debian. Building it on our architectures went fine, expect mips64el [1]. Relevant parts hopefully:
g++ -fPIC -fvisibility=hidden -fstack-protector -pthread -std=c++11 -D_REENTRANT  -g -O2 -fdebug-prefix-map=/[PKGBUILDDIR]=. -fstack-protector-strong -Wformat -Werror=format-security -DBOTAN_IS_BEING_BUILT -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor  -Ibuild/include -c /[PKGBUILDDIR]/src/lib/rng/processor_rng/processor_rng.cpp -o build/obj/lib/rng_processor_rng.o

    /tmp/ccWEmBZw.s: Assembler messages:
    /tmp/ccWEmBZw.s:485: Error: unrecognized opcode: `darn'
    /tmp/ccWEmBZw.s:490: Error: unrecognized opcode: `darn'
    /tmp/ccWEmBZw.s:559: Error: unrecognized opcode: `darn'
    /tmp/ccWEmBZw.s:564: Error: unrecognized opcode: `darn'
[1] https://buildd.debian.org/status/fetch.php?pkg=botan&arch=ppc64el&ver=2.17.0%2Bdfsg-1&stamp=1604614046&raw=0

**Comment by randombit** [comment] 2020-11-07 13:04
This build is using binutils_2.35.1-2 which is seemingly latest version. So this seems like a binutils regression to me - I can build this file fine using `as 2.27-43` (from RHEL7). And the code in question has been in place and unchanged since 2.15.0, which built fine even in Debian (AFAIK), another reason to suspect a regression. I don't see anything in the binutils or gas changelogs which seems to indicate there was a deliberate change here. Is it possible to force the Debian build to use an older binutils on ppc64 to test this theory?

**Comment by randombit** [comment] 2020-11-07 13:08
Mystery deepens as here https://buildd.debian.org/status/fetch.php?pkg=botan&arch=ppc64el&ver=2.16.0%2Bdfsg-2&stamp=1604260042&raw=0 same code builds fine, and with same binutils version ...

**Comment by gcsideal** [comment] 2020-11-07 15:57
Some bits. Debian PPC64el CPU support[1] says it runs on POWER8 processors and above. Our friend @noloader  notes:
```
The DARN generator is like x86's RDRAND and RDSEED. The DARN generator
is POWER9 and above. It is supported in recent compilers, but not
older compilers.
```
I suspect this can be behind the curtains as the build host is different for the two tries. Compilation is fine on ppc64el-osuosl-01 but not on ppc64el-unicamp-01 i.e. the former can be a POWER9 machine and the latter is a POWER8 one. I have POWER8 access, can test some things on it.
Until then @noloader also states (in Crypto++)
```
We use inline assembly and byte codes to avoid the need for compiler
support [2].
```
See the code guards GCC_DARN_ASM_AVAILABLE and _ARCH_PWR9 which also shows GCC has builtin for DARN: "__builtin_darn()".

Hope this helps.
[1] https://wiki.debian.org/ppc64el#Required_Hardware
[2] https://github.com/weidai11/cryptopp/blob/master/darn.cpp#L85

**Comment by randombit** [comment] 2020-11-07 18:23
I don't believe this is a compiler issue since we also avoid the intrinsics and use inline asm (because of https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91481 - the intrinsic is broken and insecure on many versions of GCC)

And definitely yes DARN is only for POWER9, but all use of the instructions are gated behind a CPUID check (using `getauxval(AT_HWCAP2)`) and here the problem is not that the instruction is being executed when it shouldn't be (which would cause a `SIGILL` at runtime) but that the assembler doesn't recognize the instruction at all. FWIW everything compiles and runs fine on gcc112 which is a POWER8 machine. [Of course the instruction is not available so `Processor_RNG` cannot be used, but everything compiles]

**Comment by gcsideal** [comment] 2020-11-07 21:58
> I don't believe this is a compiler issue since we also avoid the intrinsics and use inline asm (because of https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91481 - the intrinsic is broken and insecure on many versions of GCC)

Maybe it is, due to Debian changes. The compiler package version is changed from 10.2.0-15 to 10.2.0-16 which reveals several fixes from upstream Git tree got included [1]. Also contains addition of some additional checks, which is cryptic to me: "Also enable the extra checking on amd64, arm64, ppc64el, s390x, [...]". Will do a package version diff to find out what does it mean.

> And definitely yes DARN is only for POWER9, but all use of the instructions are gated behind a CPUID check (using `getauxval(AT_HWCAP2)`) and here the problem is not that the instruction is being executed when it shouldn't be (which would cause a `SIGILL` at runtime) but that the assembler doesn't recognize the instruction at all. FWIW everything compiles and runs fine on gcc112 which is a POWER8 machine. [Of course the instruction is not available so `Processor_RNG` cannot be used, but everything compiles]

Wild guess that the mentioned extra checking may mean GCC now recognize it is going to compile in DARN usage that the current architecture (the POWER8 CPU on which GCC compiles) is not supported (and will cause SIGILL if run). Thus it choose to fail early and report DARN can't be used on that CPU.
Can PPC64el with POWER8 CPU be emulated on AMD64 CPU? Would make it possible to test this case on my machine.
[1] https://packages.qa.debian.org/g/gcc-10/news/20201029T160331Z.html

**Comment by noloader** [comment] 2020-11-08 00:09
Hi Everyone,

My apologies if I am mis-parsing things. Based on this:

```
g++ -fPIC -fvisibility=hidden -fstack-protector -pthread -std=c++11 -D_REENTRANT
 -g -O2 -fdebug-prefix-map=/[PKGBUILDDIR]=. -fstack-protector-strong -Wformat -W
error=format-security -DBOTAN_IS_BEING_BUILT -Wall -Wextra -Wpedantic -Wstrict-a
liasing -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-a
s-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -c /[PKGBUILDDIR]/src
/lib/rng/processor_rng/processor_rng.cpp -o build/obj/lib/rng_processor_rng.o
```

I believe `-mcpu=power9` is missing from the compile line. If using XLC, I believe the options of interest are `-qarch=pwr9 -qaltivec`.

The linker on x86 has different behavior than ARM and PPC. On x86, the linker will assemble without an arch or cpu option. On ARM and PPC, you have to use an arch or cpu option to enable the ISA in both the compiler and linker. Very annoying.

**Comment by randombit** [comment] 2020-11-08 09:13
@noloader Interesting theory, worth a try. @gcsideal can you try #2466? That PR is against master but it should apply cleanly to 2.17.1

@gcsideal `qemu` supports POWER8, not sure if Debian has the ppc64 system libraries available though.

**Comment by randombit** [comment] 2020-11-08 09:23
Another possible fix would be to just use the `.byte` binary encoding of the instruction, though that is a frustrating resolution since clearly older versions of `as` support the instruction just fine.

**Comment by randombit** [comment] 2020-11-08 09:59
Sadly #2466 definitely doesn't resolve the issue since it doesn't even compile. Its unclear if it is even possible to use `__attribute__((target(...)))` to enable support for DARN

**Comment by gcsideal** [comment] 2020-11-09 17:53
> I believe `-mcpu=power9` is missing from the compile line. If using XLC, I believe the options of interest are `-qarch=pwr9 -qaltivec`.
> 
> The linker on x86 has different behavior than ARM and PPC. On x86, the linker will link objects without an arch or cpu option. On ARM and PPC, you have to use an arch or cpu option to enable the ISA in both the compiler and linker. On ARM and PPC, if the linker sees instructions for an ISA without the ISA enabled, then it will fail. Very annoying.

@noloader: if I reincarnate I would like to have as much knowledge like you have. Created a POWER8 Qemu environment. Assembler choke on the 'darn' opcode. But if I extend the g++ call with the mentioned -mcpu=power9 switch, then processor_rng.cpp compiles just fine. It seems it's need to be noted to be passed for the assembler.

**Comment by randombit** [comment] 2020-11-09 19:28
Thanks for running this down @gcsideal, and @noloader thanks for suggesting that as a possible issue, I hadn't seen that before and really didn't expect it as a possible cause. I'll push a fix tonight.

**Comment by mouse07410** [comment] 2020-11-09 23:12
I confirm that issue (absence of the appropriate flag prevents the compiler from generating the related instructions). E.g., Apple x86_64, you need `-maes -mpcmul` to get full AESNI support.

**Comment by randombit** [comment] 2020-11-10 12:20
Fixed now in master and release-2 branch. I'll hold off a few days before making a new patch release since we just had one. @gcsideal if you want to backport immediately 6e4d3ee91ab19 is the patch you're looking for. Thanks for the report and again @noloader thanks for the help

**Closed by randombit** 2020-11-10 12:20 UTC
Labels: build problem

**Comment by randombit** [comment] 2020-11-13 15:20
2.17.2 has been released including this patch
