### ISSUE TITLE
"PRNG not seeded" error

### ISSUE THREAD

**Issue by FuckingCoder** [randombit/botan#715] opened 2016-11-05 07:42 UTC
Hi! I make Autoseeded_RNG in multithread and I got this ("PRNG not seeded: HMAC_RNG(HMAC(SHA-512),HMAC(SHA-512))") error in some threads while try to use RNG. Why?

**Comment by cordney** [comment] 2016-11-05 09:14
Can you please post your code? It's hard to judge from just the multithreaded what the issue might be. Please also tell us which Botan version you are using, there have been changes to the RNGs recently.

**Comment by randombit** [comment] 2016-11-05 09:56
This is coming from a version at least a few behind, since AutoSeeded_RNG has used HMAC_DRBG since 1.11.31. But I'm not aware of any problems that would have caused this type of error in any recent version.

**Comment by FuckingCoder** [comment] 2016-11-05 11:55
Botan version: 1.11.29. Code:

`			RNG.reset(new Botan::AutoSeeded_RNG());
 			_x.randomize(*RNG, 128 * 8 - 1);

`

**Comment by cordney** [comment] 2016-11-05 12:11
Of which type is `_x`? Can you please post variable declarations as well? And how are you using this code in a multithreaded application? You have to give us some more information, so we can track this down.

**Comment by FuckingCoder** [comment] 2016-11-05 12:14
Yes. I use this code in multithreaded app. 

boost::shared_ptr<Botan::RandomNumberGenerator> RNG;
Botan::BigInt _x
RNG.reset(new Botan::AutoSeeded_RNG());
 _x.randomize(*RNG, 128 * 8 - 1);

**Comment by cordney** [comment] 2016-11-05 12:54
From looking at 1.11.31's `HMAC_RNG::randomize()` it seems to me that seeding the RNG with the first `reseed()` did not collect enough entropy bits (256) from the entropy sources within the default timeout of 50 milliseconds, hence the exception. I assume you haven't modified `BOTAN_RNG_RESEED_DEFAULT_TIMEOUT` in build.h? Which platform are you running this code on?

Your example code does not show any multithreaded environment. See, what we need to do is to have code that triggers the exception, so we can debug it to track down the issue. If you can not post your full multithreaded application's code here you have to give us some more information on the context of the code block above or post a minimal example that triggers the exception.

**Comment by FuckingCoder** [comment] 2016-11-10 15:34
I'm use Botan 1.11.29. 
My multithreading code:
```
void threadsThread(int threadNumber)
{
  boost::shared_ptr<Botan::RandomNumberGenerator> RNG;
  RNG.reset(new Botan::AutoSeeded_RNG());
 _x.randomize(*RNG, 128);
}
    boost::thread_group threads;
    for (int i = 0; i < 40000; ++i)
    {
          boost::thread* th = new boost::thread(& threadsThread, i);
	  threads.add_thread(th);
    }

```

Can I use Boost random for randomization BigInt?

**Comment by randombit** [comment] 2016-11-10 15:42
The following code runs without problems on my 4 core i7:

```
#include <boost/thread.hpp>
#include <botan/auto_rng.h>
#include <botan/bigint.h>

void threadsThread(int threadNumber)
{
  boost::shared_ptr<Botan::RandomNumberGenerator> RNG;
  RNG.reset(new Botan::AutoSeeded_RNG());
  Botan::BigInt x;
  x.randomize(*RNG, 128);
  std::cout << x << "\n";
}

int main() {
    boost::thread_group threads;
    for (int i = 0; i < 4000; ++i)
    {
    try {
    boost::thread* th = new boost::thread(& threadsThread, i);
      threads.add_thread(th);
    }
    catch(std::exception& e)
       {
       std::cout << e.what() << "\n";
       }
    }
    threads.join_all();
}
```

And, no there is no support for calling Boost RNG or the like.

**Comment by FuckingCoder** [comment] 2016-11-10 15:48
I catch error "PRNG not seeded: HMAC_RNG(HMAC(SHA-512),HMAC(SHA-512))" in thread function on Botan 1.11.29

**Comment by mouse07410** [comment] 2016-11-10 20:40
> The following code runs without problems on my 4 core i7...

Weird - that code doesn't even compile on my machine (4 core i7, Mac OS X 10.11.6, Xcode-8.1, current github master of Botan-1.11):
```
$ clang++ -Wno-c++11-extensions ${CFLAGS} -o botan-test1 -I/opt/local/include -I/opt/local/include/botan-1.11 botan-test1.cpp -L/opt/local/lib -lbotan-1.11 -lboost_system-mt -lboost_random-mt -lboost_thread-mt
In file included from botan-test1.cpp:2:
In file included from /opt/local/include/botan-1.11/botan/auto_rng.h:11:
In file included from /opt/local/include/botan-1.11/botan/rng.h:11:
In file included from /opt/local/include/botan-1.11/botan/entropy_src.h:11:
/opt/local/include/botan-1.11/botan/secmem.h:49:25: error: expected ';' at end of
      declaration list
      secure_allocator() BOTAN_NOEXCEPT {}
                        ^
                        ;
/opt/local/include/botan-1.11/botan/secmem.h:113:77: error: a space is required between
      consecutive right angle brackets (use '> >')
template<typename T> using secure_vector = std::vector<T, secure_allocator<T>>;
                                                                            ^~
                                                                            > >
/opt/local/include/botan-1.11/botan/secmem.h:114:75: error: a space is required between
      consecutive right angle brackets (use '> >')
template<typename T> using secure_deque = std::deque<T, secure_allocator<T>>;
                                                                          ^~
                                                                          > >
In file included from botan-test1.cpp:2:
In file included from /opt/local/include/botan-1.11/botan/auto_rng.h:11:
In file included from /opt/local/include/botan-1.11/botan/rng.h:13:
/opt/local/include/botan-1.11/botan/exceptn.h:26:19: error: exception specification of
      overriding function is more lax than base version
      const char* what() const BOTAN_NOEXCEPT override { return m_msg.c_str(); }
                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/exception:96:25: note: 
      overridden virtual function is here
    virtual const char* what() const _NOEXCEPT;
                        ^
In file included from botan-test1.cpp:2:
In file included from /opt/local/include/botan-1.11/botan/auto_rng.h:11:
In file included from /opt/local/include/botan-1.11/botan/rng.h:13:
/opt/local/include/botan-1.11/botan/exceptn.h:26:31: error: expected ';' at end of
      declaration list
      const char* what() const BOTAN_NOEXCEPT override { return m_msg.c_str(); }
                              ^
                              ;
/opt/local/include/botan-1.11/botan/exceptn.h:24:52: error: member initializer 'm_msg' does
      not name a non-static data member or base class
      explicit Exception(const std::string& msg) : m_msg(msg) {}
                                                   ^~~~~~~~~~
/opt/local/include/botan-1.11/botan/exceptn.h:25:63: error: member initializer 'm_msg' does
      not name a non-static data member or base class
  ...char* prefix, const std::string& msg) : m_msg(std::string(prefix) + " " + msg) {}
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from botan-test1.cpp:2:
In file included from /opt/local/include/botan-1.11/botan/auto_rng.h:11:
/opt/local/include/botan-1.11/botan/rng.h:208:17: error: exception specification of
      overriding function is more lax than base version
class BOTAN_DLL Serialized_RNG final : public RandomNumberGenerator
                ^
/opt/local/include/botan-1.11/botan/rng.h:28:15: note: overridden virtual function is here
      virtual ~RandomNumberGenerator() = default;
              ^
In file included from botan-test1.cpp:2:
/opt/local/include/botan-1.11/botan/auto_rng.h:88:7: error: exception specification of
      overriding function is more lax than base version
      ~AutoSeeded_RNG();
      ^
/opt/local/include/botan-1.11/botan/rng.h:28:15: note: overridden virtual function is here
      virtual ~RandomNumberGenerator() = default;
              ^
In file included from botan-test1.cpp:1:
In file included from /opt/local/include/boost/thread.hpp:13:
In file included from /opt/local/include/boost/thread/thread.hpp:12:
In file included from /opt/local/include/boost/thread/thread_only.hpp:17:
In file included from /opt/local/include/boost/thread/pthread/thread_data.hpp:10:
In file included from /opt/local/include/boost/thread/exceptions.hpp:20:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:439:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:628:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:1678:25: error: 
      no member named 'max_size' in 'Botan::secure_allocator<unsigned char>'
            {return __a.max_size();}
                    ~~~ ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:1540:17: note: 
      in instantiation of member function
      'std::__1::allocator_traits<Botan::secure_allocator<unsigned char> >::__max_size'
      requested here
        {return __max_size(__has_max_size<const allocator_type>(), __a);}
                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:952:50: note: 
      in instantiation of member function
      'std::__1::allocator_traits<Botan::secure_allocator<unsigned char> >::max_size'
      requested here
    return _VSTD::min<size_type>(__alloc_traits::max_size(this->__alloc()), numeric_...
                                                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:929:15: note: 
      in instantiation of member function 'std::__1::vector<unsigned char,
      Botan::secure_allocator<unsigned char> >::max_size' requested here
    if (__n > max_size())
              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:1073:9: note: 
      in instantiation of member function 'std::__1::vector<unsigned char,
      Botan::secure_allocator<unsigned char> >::allocate' requested here
        allocate(__n);
        ^
/opt/local/include/botan-1.11/botan/rng.h:135:30: note: in instantiation of member function
      'std::__1::vector<unsigned char, Botan::secure_allocator<unsigned char> >::vector'
      requested here
         secure_vector<byte> output(bytes);
                             ^
In file included from botan-test1.cpp:1:
In file included from /opt/local/include/boost/thread.hpp:13:
In file included from /opt/local/include/boost/thread/thread.hpp:12:
In file included from /opt/local/include/boost/thread/thread_only.hpp:17:
In file included from /opt/local/include/boost/thread/pthread/thread_data.hpp:10:
In file included from /opt/local/include/boost/thread/exceptions.hpp:20:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:439:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:628:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:1488:21: error: 
      no member named 'allocate' in 'Botan::secure_allocator<unsigned char>'
        {return __a.allocate(__n);}
                ~~~ ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:931:53: note: 
      in instantiation of member function
      'std::__1::allocator_traits<Botan::secure_allocator<unsigned char> >::allocate'
      requested here
    this->__begin_ = this->__end_ = __alloc_traits::allocate(this->__alloc(), __n);
                                                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:1073:9: note: 
      in instantiation of member function 'std::__1::vector<unsigned char,
      Botan::secure_allocator<unsigned char> >::allocate' requested here
        allocate(__n);
        ^
/opt/local/include/botan-1.11/botan/rng.h:135:30: note: in instantiation of member function
      'std::__1::vector<unsigned char, Botan::secure_allocator<unsigned char> >::vector'
      requested here
         secure_vector<byte> output(bytes);
                             ^
In file included from botan-test1.cpp:1:
In file included from /opt/local/include/boost/thread.hpp:13:
In file included from /opt/local/include/boost/thread/thread.hpp:12:
In file included from /opt/local/include/boost/thread/thread_only.hpp:17:
In file included from /opt/local/include/boost/thread/pthread/thread_data.hpp:10:
In file included from /opt/local/include/boost/thread/exceptions.hpp:20:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:439:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:628:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:1496:14: error: 
      no member named 'deallocate' in 'Botan::secure_allocator<unsigned char>'
        {__a.deallocate(__p, __n);}
         ~~~ ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:452:25: note: 
      in instantiation of member function
      'std::__1::allocator_traits<Botan::secure_allocator<unsigned char> >::deallocate'
      requested here
        __alloc_traits::deallocate(__alloc(), __begin_, capacity());
                        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:1244:75: note: 
      in instantiation of member function 'std::__1::__vector_base<unsigned char,
      Botan::secure_allocator<unsigned char> >::~__vector_base' requested here
    template <class _Tp, class _Alloc> friend class _LIBCPP_TYPE_VIS_ONLY vector;
                                                                          ^
In file included from botan-test1.cpp:1:
In file included from /opt/local/include/boost/thread.hpp:13:
In file included from /opt/local/include/boost/thread/thread.hpp:12:
In file included from /opt/local/include/boost/thread/thread_only.hpp:17:
In file included from /opt/local/include/boost/thread/pthread/thread_data.hpp:10:
In file included from /opt/local/include/boost/thread/exceptions.hpp:20:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:439:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:628:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:1496:14: error: 
      no member named 'deallocate' in 'Botan::secure_allocator<unsigned long long>'
        {__a.deallocate(__p, __n);}
         ~~~ ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:452:25: note: 
      in instantiation of member function
      'std::__1::allocator_traits<Botan::secure_allocator<unsigned long long> >::deallocate'
      requested here
        __alloc_traits::deallocate(__alloc(), __begin_, capacity());
                        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:1244:75: note: 
      in instantiation of member function 'std::__1::__vector_base<unsigned long long,
      Botan::secure_allocator<unsigned long long> >::~__vector_base' requested here
    template <class _Tp, class _Alloc> friend class _LIBCPP_TYPE_VIS_ONLY vector;
                                                                          ^
13 errors generated.
$
```

**Comment by randombit** [comment] 2018-03-05 02:54
Closing as we cannot reproduce. If the issue still occurs with latest version please open a new issue.

**Closed by randombit** 2018-03-05 02:54 UTC

**Comment by nunojpg** [comment] 2019-03-01 13:48
Just for reference this might mean module system_rng was not enabled.
