### ISSUE TITLE
"dc" (domainComponent) part of CA certificate's subject name is missing in CRL's issuer field

### ISSUE THREAD

**Issue by RavilN** [randombit/botan#1252] opened 2017-10-12 19:21 UTC
[CA.zip](https://github.com/randombit/botan/files/1380397/CA.zip)

I used CA certificate created by third party tool to create new CRL. That CA Certificate in the subject name has domainComponent part, among with commonName, country, etc.
Generated CRL, exported into file, does not have that domainComponent in its "Issuer" field.
As a result, in another application, which uses CA certificate and CRL, verification of CRL fails, because its issuer does not match with subject name of the CA certificate (dc component is missing in CRL).

In the attached zip: 

- opcuactt_ca.der - CA Public key;
- opcuactt_ca.pem - CA private Key;
- revocation_list_opcuactt_ca.crl - the CRL, generated by third party tool;
- revocation_li

st_opcuactt_ca-generated-by-Botan-and-exported.crl - the CRL, generated by Botan (this one is updated one, new CRL has the same issue with issuer).

**Comment by randombit** [comment] 2017-10-19 22:21
Confirmed. The problem is we recreate the DN from memory, and in doing so ignore fields we don't know about. This is fixed by #884 (a WIP but expected to be finished before next release.)

**Comment by randombit** [comment] 2017-11-14 00:25
@RavilN I have not yet created a test to reproduce your issue, but I believe it is resolved by the changes in #844 which are now functionally complete. If you are able to test your application against that PR branch to confirm, that would be very nice.

**Comment by randombit** [comment] 2017-11-14 17:35
Created a test, fix confirmed. Closing this issue. @RavilN thank you very much for the report, this should be fixed in the upcoming 2.4.0 release.

**Closed by randombit** 2017-11-14 17:35 UTC
