### ISSUE TITLE
Various tests fail when using the bsi policy

### ISSUE THREAD

**Issue by fweissberg** [randombit/botan#1362] opened 2017-12-19 12:15 UTC
In particular, the BSI policy forbids the module emsa_pkcs1.  The unit test simply fails because the algorithm cannot be looked up (RSA uses emsa_pkcs1). While the unit tests do detect if the sig_algo (e.g. RSA) is not available, they do not notice if the particular AlgorithmIdentifier (including padding/encoding if applicable) is not available.
For the other tests, when reading the certificate, m_self_signed remains set to false even for trusted, self-signed root CAs because the signature cannot be verified (for the same reason as above). This results in a loop when validating certificate paths: the root CA is processed two times in a row as it appears not to be self-signed, even if subject_dn == issuer_dn.

`./configure.py --with-debug-info --module-policy bsi --enable-modules x509`

[fails.txt](https://github.com/randombit/botan/files/1571597/fails.txt)

**Comment by randombit** [comment] 2017-12-19 15:09
Confirmed, thanks.

I have a fix for the issue of self-signed vs self-issued detection (basically, if the algorithm can't be found, we assume it is self-signed, which seem safe since it is self-issued we won't be able to verify it in any case). However now all the test fail with the (newly introduced) error "Certificate signed with unknown/unavailable algorithm" since PKCSv1.5 signatures are still disabled. (#1364)

I can see a few options for resolution of the failing tests:
 1) disable these tests when PKCSv1.5 signatures are not enabled in the build, since we know the data in them is PKCSv1.5 RSA
 2) modify tests to accept "unknown algorithm" as an acceptable result
 3) add PKCSv1.5 as a dependency on `x509` since ~99% of RSA certs use it.
 4) regenerate all the test data using PSS (but that doesn't really solve the problem, since the tests will still fail if PSS is disabled).

Not really sure what the best thing to do is, leaning to 1 as the simplest choice.

Paging @securitykernel as interested party re BSI policy

**Comment by securitykernel** [comment] 2017-12-20 08:50
I think 3 and 4 are not an option. 1 and 2 are both acceptable.

**Comment by randombit** [comment] 2017-12-20 15:05
Went with 1, fixed in 646ed79e273f8

**Closed by randombit** 2017-12-20 15:05 UTC
