### ISSUE TITLE
How to modify the certificate size limit when deploying a TLS server

### ISSUE THREAD

**Issue by shilohshi** [randombit/botan#4400] opened 2024-10-23 08:36 UTC
Hi, I have noticed that when deploying a server using [botan](https://github.com/randombit/botan) or [botan-tls-testserver](https://github.com/reneme/botan-tls-testserver), there seems to be a direct or indirect limit on certificate size in the code. Specifically, when the server certificate exceeds a certain size (e.g., over around 120KB), the client receives an `ERR_SSL_PROTOCOL_ERROR` upon subsequent access. I would greatly appreciate any guidance on how to manually modify this size limit. Thank you!

**Comment by randombit** [comment] 2024-10-23 11:36
Thanks for the report. I’m not sure offhand why this would occur and it certainly seems like a bug.

Am I understanding correctly that the situation is that if the server is provisioned with a large cert, then upon connecting, the *client* receives the alert?

Which version(s) have you tried?

Also if you force the client to connect using TLS v1.2 vs v1.3 do you see any difference in behavior?

**Comment by randombit** [comment] 2024-10-23 11:53
Interesting with OpenSSL cli I instead get

> 805B7CF4EC770000:error:0A000098:SSL routines:read_state_machine:excessive message size:ssl/statem/statem.c:647:

both TLS 1.2 or TLS 1.3

**Comment by reneme** [comment] 2024-10-23 13:00
For the record: There is `size_t TLS_Policy::maximum_certificate_chain_size()` which allows configuring the maximum size of the transferred certificate chain in bytes. Though, this is set to `0` (unlimited) by default.

**Comment by reneme** [comment] 2024-10-23 13:42
> Interesting with OpenSSL cli I instead get
> ```
> 805B7CF4EC770000:error:0A000098:SSL routines:read_state_machine:excessive message size:ssl/statem/statem.c:647:
> ```

OpenSSL seems to restrict the CERTIFICATE message to 100kB by default: https://github.com/openssl/openssl/blob/e1886edf4bffef7663eb5bb4bee43d0232d8b68d/include/openssl/ssl.h.in#L663-L664

> Was able to replicate this with master. Only affects TLS 1.3, errors with "No sufficient server certificate available"

_It works for me, actually!_ The error message you're seeing (@randombit) indicates that the server didn't find a suitable certificate in the `Credentials_Manager`. I adapted your certificate creation program slightly (`CN=localhost` and `more_dns.push_back("localhost")`) and it worked for me, using `./botan tls_server ...` and `./botan tls_client localhost`. Both for TLS 1.3 and 1.2.

For the record: the resulting certificate is about 200kB in DER format.

**Comment by reneme** [comment] 2024-10-23 13:49
@shilohshi could it be that your client relies on OpenSSL internally? Then you might actually be running into a client-side limit rather than on the server.

Please try this against your Botan-based server with the large certificate configured:
```
openssl s_client -connect your.domain:443 -servername your.domain -debug
```

If this prints 100+kB of hex barf, you are receiving your certificate from the server but OpenSSL aborts the connection because of the limitation mentioned in my previous post. If so, try again without the `-debug` and you should see what Jack saw, namely:

```
> openssl s_client -connect your.domain:443 -servername your.domain
40679B56567F0000:error:0A000098:SSL routines:read_state_machine:excessive message size:../ssl/statem/statem.c:610
```

**Comment by shilohshi** [comment] 2024-10-23 15:21
Thank you very much for your prompt response! @randombit @reneme  

I am using Botan version 3.3.0, and I deployed a website using the following command:

```
botan tls_http_server large_cert.crt large_cert.key
```

with the certificate (172KB) and key provided below:
[large_cert_and_key.zip](https://github.com/user-attachments/files/17494205/large_cert_and_key.zip)

However, when I access the URL of my deployed website in Chrome, I receive the `ERR_SSL_PROTOCOL_ERROR` message.  At this point, the error message displayed by the Botan server is as follows:

```
Session: illegal_parameter [Botan TLS Alert:47]
```

If I switch to the following certificate (78KB) and key, then, the above error message will not be received:
[small_cert_and_key.zip](https://github.com/user-attachments/files/17494365/small_cert_and_key.zip)

<br>

> For the record: There is `size_t TLS_Policy::maximum_certificate_chain_size()` which allows configuring the maximum size of the transferred certificate chain in bytes. Though, this is set to `0` (unlimited) by default.

If I understand correctly, does this mean that Botan does not impose any restrictions on the size of certificates or TLS records by default? If that is the case, does it imply that the access issues are actually originating from the browser rather than the server deployed with Botan? 

Thank you very much for your assistance!

**Comment by randombit** [comment] 2024-10-23 20:15
BoringSSL seems to have the same 100 kb limit on the chain, presumably inherited from OpenSSL, so Chrome likely rejects any chains larger.

**Comment by shilohshi** [comment] 2024-10-24 01:43
I see, thank you very much for your explanation!

**Comment by reneme** [comment] 2024-10-24 06:32
Closing as 'not a bug'.

**Closed** 2024-10-24 06:32 UTC
Labels: bug
