### ISSUE TITLE
Segmentation fault in util test

### ISSUE THREAD

**Issue by Exaeta** [randombit/botan#1260] opened 2017-10-16 15:32 UTC
After running `./botan-test` the test segfaulted. Running termux on Nexus 6.
```
$ ./botan-test
[...]
util:
Segmentation fault
```
Configured with:
```
$ python ./configure.py --disable-modules=newhope --cpu=armv7a --cc=clang
```
Is there a way I can configure it with `-fsanitize=undefined` and `-fsanitize=address` etc?

**Comment by Exaeta** [comment] 2017-10-16 15:33
was --cpu. For some reason I can't edit this on my phone.

**Comment by mgierlings** [comment] 2017-10-16 15:37
`--with-sanitizers` is what you're looking for. BTW `./configure.py --help` lists all available options.

**Comment by randombit** [comment] 2017-10-17 17:56
That is both unfortunate and highly unexpected. Looking at the test there really doesn't seem to be any reason for a crash to ever happen in there. Does it also crash if you just run the `util` tests directly (ie `./botan-test util`)? If you are able to get a backtrace that would probably help.

**Comment by Exaeta** [comment] 2017-10-17 19:06
It also crashes with just ./botan-test util. 

I'm re-building with debug information.

**Comment by randombit** [comment] 2018-03-21 18:46
@Exaeta were you able to get a backtrace or other debug info for this? As we cannot reproduce, without further information it will be hard to fix the problem.

**Comment by randombit** [comment] 2018-03-28 10:48
Closing as without more info we cannot diagnose.

**Closed by randombit** 2018-03-28 10:48 UTC
Labels: bug, needs more info
