### ISSUE TITLE
BSI path validation ran 788 tests in 4.47 sec 64 FAILED (winx64)

### ISSUE THREAD

**Issue by InfinityMin3r** [randombit/botan#2369] opened 2020-06-13 01:15 UTC
Hello,

I am on Windows 10, using the 2017 x64 native tools.

nmake works fine, but nmake check fails many of the BSI validation tests with errors such as:

"
Failure 1: BSI path validation cert_path_algo_strength_01 path validation result produced unexpected result 'Certificate issuer not found' expected 'Hash function used is considered too weak for security'
Failure 2: BSI path validation cert_path_algo_strength_01 path validation result produced unexpected result 'Certificate issuer not found' expected 'Hash function used is considered too weak for security'
Failure 3: BSI path validation cert_path_algo_strength_01 path validation result produced unexpected result 'Certificate issuer not found' expected 'Hash function used is considered too weak for security'
Failure 4: BSI path validation cert_path_algo_strength_01 path validation result produced unexpected result 'Certificate issuer not found' expected 'Hash function used is considered too weak for security'
Failure 5: BSI path validation cert_path_algo_strength_01 path validation result produced unexpected result 'Certificate issuer not found' expected 'Hash function used is considered too weak for security'
Failure 6: BSI path validation cert_path_algo_strength_01 path validation result produced unexpected result 'Certificate issuer not found' expected 'Hash function used is considered too weak for security'
Failure 7: BSI path validation cert_path_algo_strength_01 path validation result produced unexpected result 'Certificate issuer not found' expected 'Hash function used is considered too weak for security'
Failure 8: BSI path validation cert_path_algo_strength_01 path validation result produced unexpected result 'Certificate issuer not found' expected 'Hash function used is considered too weak for security'
Failure 9: BSI path validation cert_path_algo_strength_01 path validation result produced unexpected result 'Certificate issuer not found' expected 'Hash function used is considered too weak for security'
"

Essentially all the tests return Certificate issuer not found...

Any help would be greatly appreciated!

**Comment by InfinityMin3r** [comment] 2020-06-13 01:49
Just to make sure it isn't explicitly my system, I just tried botan 2.13 and it works fine.

**Comment by randombit** [comment] 2020-06-13 15:38
Strange! Just to clarify you are seeing this problem using latest `master`?

**Comment by InfinityMin3r** [comment] 2020-06-13 18:55
No, I'm on 2.14.0 as downloaded and verified from the website...

**Comment by randombit** [comment] 2020-06-13 19:06
These are the only tests that fail? Can you post your specific compiler version (eg output of running `cl` on command line)

**Comment by seppy87** [comment] 2020-07-17 23:17
Does BSI stand for "Bundesministerium für Sicherheit in der Informationstechnik"? Federal Office for Information Security.

**Comment by Prototype0** [comment] 2020-08-16 17:12
Hi, I've found the same errors.

I'm on Windows 8.1, with the VS 2017 x64 native tools.
Compiling Botan 2.15.0 release downloaded from the website.
```
> cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27024.1 for x64
```

Those are the only 64 tests that fail, same as above they all fail with 'Certificate issuer not found'.
```
> python configure.py --cc=msvc --msvc-runtime=MTd --debug-mode --with-debug-info --disable-shared
> nmake
> nmake check
... snipped "all ok" ...
BSI path validation ran 788 tests in 63.12 sec 64 FAILED
Failure 1: BSI path validation cert_path_algo_strength_01 path validation result produced unexpected result 'Certificate issuer not found' expected 'Hash function used is considered too weak for security'
Failure 2: BSI path validation cert_path_algo_strength_01 path validation result produced unexpected result 'Certificate issuer not found' expected 'Hash function used is considered too weak for security'
...
Failure 32: BSI path validation cert_path_algo_strength_02 path validation result produced unexpected result 'Certificate issuer not found' expected 'Hash function used is considered too weak for security'
Failure 33: BSI path validation cert_path_algo_strength_03 path validation result produced unexpected result 'Certificate issuer not found' expected 'Signature error'
...
Failure 47: BSI path validation cert_path_algo_strength_03 path validation result produced unexpected result 'Certificate issuer not found' expected 'Signature error'
Failure 48: BSI path validation cert_path_algo_strength_03 path validation result produced unexpected result 'Certificate issuer not found' expected 'Signature error'
Failure 49: BSI path validation cert_path_common_13 path validation result produced unexpected result 'Certificate issuer not found' expected 'Verified'
Failure 50: BSI path validation cert_path_common_13 path validation result produced unexpected result 'Certificate issuer not found' expected 'Verified'
...
Failure 64: BSI path validation cert_path_common_13 path validation result produced unexpected result 'Certificate issuer not found' expected 'Verified'
x509_path_extended:
Extended X509 path validation ran 3 tests in 714.14 msec all ok
... snipped "all ok" ...
Tests complete ran 2639631 tests in 578.18 sec 64 tests failed
ERROR:root:Error running .\botan-test.exe --data-dir=src\tests/data
```

**Comment by InfinityMin3r** [comment] 2020-08-16 21:48
Sorry, kinda dropped off the earth. I will find my compiler version.

**Comment by randombit** [comment] 2020-08-18 13:47
@Prototype0 Thanks for reporting this. Can you test 2.13.0 release also and see if that succeeds?

Unfortunately this is not reproducing in CI so I'm not sure what to make of it. What locales are you both using? Are you sure your local clocks are correct?

**Comment by Prototype0** [comment] 2020-08-18 18:17
I have now compiled the 2.13.0 release downloaded from the website using the same configure command as above and run `botan-test.exe` which seems to be the equivalent of `nmake check` for the older version.
```
> botan-test.exe
Tests complete ran 2636956 tests in 634.54 sec all tests ok
```
`Get-Host` in powershell reports `CurrentCulture: en-AU` and `CurrentUICulture: en-GB`. Not sure if that's what you're looking for, let me know if you've got a particular command to get the locale.

My system clock was 2.7 seconds behind according to time.is. I've synced it now so it's reported as exact by time.is and ran the 2.15.0 check again with the same result, 64 tests failed. My timezone is AEST if that's relevant.

**Comment by randombit** [comment] 2020-08-20 13:37
Thanks. The locale and current system time *shouldn't* be affecting this test but I was hoping that would give a hint.

If someone wants to try bisecting (https://git-scm.com/docs/git-bisect) to find the commit that introduces the failure that would probably be enough to determine the issue.

**Comment by randombit** [comment] 2023-03-25 12:26
I was able to replicate this with command line `7z` on Linux. It appears that 7Zip silently truncates paths that are longer than 100 characters.

**Comment by randombit** [comment] 2023-03-25 13:40
This is fixed now in both master and the 2.x release branch.

It turns out (TIL) that `tar` format natively has a limit of 100 characters in a pathname. However GNU tar (as well as the Python `tarfile` module) support a tar extension which enables longer paths. It appears 7Zip does not support this extension, as a result it only sees/uses the truncated path. Renaming the files so all paths are < 100 chars should do the trick.

**Closed by randombit** 2023-03-25 13:40 UTC
