### ISSUE TITLE
FreeTSA certificate fails verification

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#355] opened 2015-12-11 20:00 UTC
This is certificate of free TimeStamping Authority in Germany [https://www.freetsa.org/index_en.php]. Trying to verify it with Botan gives this:

```
$ botan version
1.11.26
$ botan cert_verify ~/Certs/freetsa.pem ~/Certs/freetsa_ca.pem 
Certificate did not validate - Signature error
$
```

OpenSSL has no problem with it:

```
$ openssl version
OpenSSL 1.0.2f-dev xx XXX xxxx (Library: OpenSSL 1.0.2e 3 Dec 2015)
[freetsa.zip](https://github.com/randombit/botan/files/59793/freetsa.zip)
$ openssl verify -verbose -CAfile ~/Certs/freetsa_ca.pem ~/Certs/freetsa.pem 
/Users/ur20980/Certs/freetsa.pem: OK
$ 
```

_Note. My `freetsa.pem` is their `tsa.crt`. My `freetsa_ca.pem` is their `cacert.pem`._

**Comment by randombit** [comment] 2015-12-18 17:29
Confirmed, thanks. It will probably require some digging to figure out the problem, but as a first step I wonder what the output looks like when you take the signature and raise it to the CA's public exponent - my initial guess is some rejects-valid problem with PKCS1 decoding, maybe?

**Comment by mouse07410** [comment] 2015-12-18 20:10
I don't know. :-(

Are there any tests that you'd like me to run/try?  I'd be happy to.

Or perhaps, since you have the offending certs, it would be quicker for you to try them?

**Comment by mouse07410** [comment] 2015-12-21 11:21
Is it possible that the mere size of the signature throws Botan off? I believe it's 8K key - haven't seen keys that big anywhere else yet.

**Comment by randombit** [comment] 2017-05-14 23:41
Might be caused by a problem like that seen in #1042

**Comment by randombit** [comment] 2018-03-05 20:30
Just checked most recent versions from their site, and (after fixing an issue around decoding the 0.0 OID which FreeTSA includes in their cert policy for whatever reason), verification works:

```
./botan cert_verify ~/Downloads/tsa.crt ~/Downloads/cacert.pem
Certificate passes validation checks
```

Unclear if this was a bug in botan that was fixed at some point, or a problem with the previous FreeTSA certs, but in any case no longer an issue. Closing

**Closed by randombit** 2018-03-05 20:30 UTC
Labels: needs analysis
