### ISSUE TITLE
`tls_session_established` only accepts exception of type `Botan::TLS::TLS_Exception` as valid type for aborting handshake

### ISSUE THREAD

**Issue by marty1885** [randombit/botan#3342] opened 2023-03-04 03:19 UTC
Hi,

In the [document](https://botan.randombit.net/handbook/api_ref/tls.html) of `tls_session_established`. It states that

> If this function wishes to cancel the handshake, it can throw an exception which will send a close message to the counterparty and reset the connection state.

This seems to indicate that any exception will cause Botan to reset the connection. However, after some experiments. I find that it only accepts `Botab::TLS::TLS_Exception`. Others like `std::runtimer_error` does not work.

Maybe this is an documentation error?

**Comment by randombit** [comment] 2023-03-04 11:10
This behavior is surprising to me. Certainly if you want to control which alert is sent, you would need to throw a `TLS_Exception` to achieve that. But I would have thought any exception would be caught and end up as an internal error alert to the peer. This deserves a look, thank you for reporting this.

**Comment by reneme** [comment] 2023-03-05 15:28
I'm working on this. Currently building a regression test in `unit_tls.cpp` to see whether this is easily reproducible. Judging from the code, I'm also baffled why that wouldn't work as expected.

**Comment by reneme** [comment] 2023-03-05 15:31
I'm working on this. Currently building a regression test in `unit_tls.cpp` to see whether this is easily reproducible. Judging from the code, I'm also baffled why that wouldn't work as expected.

**Comment by reneme** [comment] 2023-03-05 17:49
Unfortunately I didn't manage to reproduce this (based on the Botan 2.x branch) with [a regression test](https://github.com/randombit/botan/pull/3348). When throwing `Botan::Invalid_Authentication_Tag` or `std::runtime_error` the peer receives a `BAD_RECORD_MAC` or `INTERNAL_ERROR` [as expected](https://github.com/randombit/botan/blob/9747b8ad75c33df958fe26bdc335521bf5c9cd83/src/lib/tls/tls_channel.cpp#L430-L449).

Could you elaborate on what faulty behaviour you are experiencing?

**Comment by reneme** [comment] 2023-03-13 07:10
Any news here? Otherwise, I'd close as "cannot reproduce" and merge #3348 to keep it that way. Also: Probably it would make sense to forward-port this to `master`.

**Comment by reneme** [comment] 2023-03-21 06:31
Closing as *not reproducible*. Please don't hesitate to re-open if you have further information, @marty1885.

**Closed by reneme** 2023-03-21 06:31 UTC
